package sophia;

import java.io.IOException;
import java.util.Collections;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * A {@code DialogBox} is a custom UI component extending {@link HBox}.
 * <p>
 * It represents a dialog consisting of a text label and a display picture.
 * Typically used to differentiate between user messages and Sophia's responses
 * in the chat window.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;
    @FXML
    private ImageView displayPicture;

    private DialogBox(String text, Image img) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
            dialog.setText(text);
            displayPicture.setImage(img);
            assert dialog != null : "fx:id=\"dialog\" was not injected: check your FXML file.";
            assert displayPicture != null : "fx:id=\"displayPicture\" was not injected.";
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Flips the dialog box horizontally so that the image is on the left and
     * the text is on the right. Also adjusts the alignment and style class
     * for messages generated by Sophia.
     */
    private void flip() {
        ObservableList<Node> tmp = FXCollections.observableArrayList(this.getChildren());
        Collections.reverse(tmp);
        getChildren().setAll(tmp);
        setAlignment(Pos.TOP_LEFT);
        dialog.getStyleClass().add("reply-label");
    }

    public static DialogBox getSophiaDialog(String s, Image i) {
        var db = new DialogBox(s, i);
        db.flip();
        return db;
    }

    public static DialogBox getUserDialog(String s, Image i) {
        return new DialogBox(s, i);
    }
}
